openapi: 3.0.1
info:
  title: OrderManagementAPI
  description: API Definition of OrderManagementAPI
  version: 1.0.0
servers:
  - url: http://localhost:8290/api
paths:
  /order:
    post:
      summary: Create Broadband Order
      parameters:
        - in: query
          name: externalOrderId
          schema:
            type: string
          required: true
          description: External Order ID as a query parameter
      requestBody:
        description: Sample Payload
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                broadbandOrder:
                  type: object
                  properties:
                    Header:
                      type: object
                      properties:
                        externalId:
                          type: string
                        timestamp:
                          type: string
                        callerID:
                          type: string
                    Body:
                      type: object
                      # Omitted for brevity – define structure as needed
            example:
              broadbandOrder:
                Header:
                  externalId: "{{externalId}}"
                  timestamp: "2025-07-01 09:52:00"
                  callerID: "SALES_APPS"
                Body:
                  orderType: "CREATE"
                  operation: "Activation"
                  revision: "1"
                  customer:
                    customerId: "00000001"
                    customerTitle: ""
                    customerName: "DEWI SARTIKA"
                    customerMarketSegment: ""
                    customerType: ""
                    phoneNumber: "+62821"
                    email: "lukman@swamedia.co.id"
                    npwp: "0000"
                    customerAddress:
                      address: "EMPU JATMIKA KAB HULU SUNGAI UTARA 71418"
                      street: "EMPU JATMIKA"
                      city: "KAB HULU SUNGAI UTARA"
                      province: "Kalimantan Selatan"
                      postalCode: "71418"
                      country: "INDONESIA"
                    billingAddress:
                      address: "EMPU JATMIKA KAB HULU SUNGAI UTARA 71418"
                      street: "EMPU JATMIKA"
                      city: "KAB HULU SUNGAI UTARA"
                      province: "Kalimantan Selatan"
                      postalCode: "71418"
                      country: "INDONESIA"
                    installationAddress:
                      address: "EMPU JATMIKA KAB HULU SUNGAI UTARA 71418"
                      street: "EMPU JATMIKA"
                      city: "KAB HULU SUNGAI UTARA"
                      province: "Kalimantan Selatan"
                      postalCode: "71418"
                      country: "INDONESIA"
                      sto: "AMT"
                      latitude: "-2.4156419736312644"
                      longitude: "115.24916990674556"
                      landmark: "Dekat Gedung PT. ABC"
                  products:
                    reservation:
                      tnReservation: "0000001"
                      portReservation: "0000002"
                      odpName: "ODP-TEST-GAMBIR1"
                      appointmentReservation: "8398486"
                      inetReservation: "0000003"
                      requestedDeliveryDatetime: "2023-10-17 17:08:45"
                    inet:
                      ndInet: "616231201654"
                      ndReff: "05276065166"
                      serviceIdInet: "00000001_616231201654_INTERNET"
                      orderType: "CREATE"
                      packages:
                        - packageName: "INETFN20M"
                          action: "ADD"
                          attributes:
                            - name: "ND"
                              value: "616231201654"
                              action: "ADD"
                            - name: "USERNAME"
                              value: "616231201654"
                              action: "ADD"
                            - name: "REALM"
                              value: "telkom.net"
                              action: "ADD"
                            - name: "UPLOAD"
                              value: "10240"
                              action: "ADD"
                            - name: "DOWNLOAD"
                              value: "20480"
                              action: "ADD"
                            - name: "ONT"
                              value: "SWONT"
                              action: "ADD"
          application/xml:
            schema:
              type: object
              xml:
                name: payload
      responses:
        default:
          description: Default response
